name: Publish Test

on:
  workflow_run:
    workflows:
      - "Bump Version"
    types:
      - "completed"
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: "echo Publish OK!!"
